### ISSUE TITLE
Missing rollup package causing CI to fail

### ISSUE THREAD

**Issue by mhkeller** [mhkeller/layercake#192]
Under investigation

```

Run npm ci --legacy-peer-deps
npm WARN deprecated text-encoding@0.6.4: no longer maintained
npm ERR! code 1
npm ERR! path /home/runner/work/layercake/layercake/node_modules/@sveltejs/kit
npm ERR! command failed
npm ERR! command sh -c node postinstall.js
npm ERR! /home/runner/work/layercake/layercake/node_modules/rollup/dist/native.js:59
npm ERR! 		throw new Error(
npm ERR! 		      ^
npm ERR! 
npm ERR! Error: Cannot find module @rollup/rollup-linux-x64-gnu. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory.
npm ERR!     at requireWithFriendlyError (/home/runner/work/layercake/layercake/node_modules/rollup/dist/native.js:59:9)
npm ERR!     at Object.<anonymous> (/home/runner/work/layercake/layercake/node_modules/rollup/dist/native.js:68:76)
npm ERR!     ... 3 lines matching cause stack trace ...
npm ERR!     at Module._load (node:internal/modules/cjs/loader:1019:12)
npm ERR!     at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:203:29)
npm ERR!     at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
npm ERR!     at async ModuleLoader.import (node:internal/modules/esm/loader:337:24)
npm ERR!     at async loadESM (node:internal/process/esm_loader:34:7) {
npm ERR!   [cause]: Error: Cannot find module '@rollup/rollup-linux-x64-gnu'
npm ERR!   Require stack:
npm ERR!   - /home/runner/work/layercake/layercake/node_modules/rollup/dist/native.js
npm ERR!       at Module._resolveFilename (node:internal/modules/cjs/loader:1140:15)
npm ERR!       at Module._load (node:internal/modules/cjs/loader:981:27)
npm ERR!       at Module.require (node:internal/modules/cjs/loader:1231:19)
npm ERR!       at require (node:internal/modules/helpers:177:18)
npm ERR!       at requireWithFriendlyError (/home/runner/work/layercake/layercake/node_modules/rollup/dist/native.js:41:10)
npm ERR!       at Object.<anonymous> (/home/runner/work/layercake/layercake/node_modules/rollup/dist/native.js:68:76)
npm ERR!       at Module._compile (node:internal/modules/cjs/loader:1364:14)
npm ERR!       at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
npm ERR!       at Module.load (node:internal/modules/cjs/loader:1203:32)
npm ERR!       at Module._load (node:internal/modules/cjs/loader:1019:12) {
npm ERR!     code: 'MODULE_NOT_FOUND',
npm ERR!     requireStack: [
npm ERR!       '/home/runner/work/layercake/layercake/node_modules/rollup/dist/native.js'
npm ERR!     ]
npm ERR!   }
npm ERR! }
npm ERR! 
npm ERR! Node.js v18.20.2

```

**Comment by mhkeller** [comment]
Fixed by https://github.com/mhkeller/layercake/blob/main/CHANGELOG.md#814
